__Autograd package__ 

In [4]:
import torch 
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
y = x + 2 
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
print(y.grad_fn)

In [9]:
z = y * y * 3 # 3*y^2
out = z.mean()

In [10]:
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [11]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [12]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [13]:
b = (a * a).sum()

In [14]:
print(b.grad_fn)

In [15]:
print(b)

tensor(47.5512, grad_fn=<SumBackward0>)


In [16]:
# GRADIENTS
print(out)

tensor(27., grad_fn=<MeanBackward1>)


In [17]:
out.backward() # out contains single scalar 

In [21]:
print(x.grad) # gradient of x 

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [22]:
x = torch.randn(3,requires_grad=True)

y = x * 2
while(y.data.norm() < 1000): 
    y = y * 2
print(y)

tensor([  576.1780, -1134.3051,  -443.0433], grad_fn=<MulBackward0>)


In [23]:
print(x)

tensor([ 0.5627, -1.1077, -0.4327], requires_grad=True)


In [24]:
#  y is no longer scalar 
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)

In [25]:
y.backward(v)

In [26]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [27]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad(): 
    print((x**2).requires_grad)

True
True
False
