__Pytorch basics__

In [6]:
# *** PYTORCH *** 
# replacement for numpy to use to power GPU 
# deep learning research platform that provides maximum flexibility and speed
import torch 

In [7]:
# tensor == Numpy ndarray 
x = torch.empty(5,3) # creating uninitialized tensor  
print(x)

tensor([[ 1.8575e+20,  4.5827e-41,  1.8575e+20],
        [ 4.5827e-41,  0.0000e+00,  4.5827e-41],
        [ 2.9855e+16,  4.5827e-41,  6.2541e+17],
        [ 4.5827e-41,  1.4013e-45,  4.5827e-41],
        [ 0.0000e+00,  0.0000e+00, -5.6858e-37]])


In [9]:
x = torch.rand(5,3) # random tensor 
print(x)

tensor([[0.3076, 0.2829, 0.1623],
        [0.6534, 0.5152, 0.7364],
        [0.4343, 0.7091, 0.3478],
        [0.9871, 0.2871, 0.8003],
        [0.8393, 0.4275, 0.8071]])


In [11]:
x = torch.zeros(5,3, dtype=torch.long) # tensor with zero and datatype long
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x = torch.tensor([5.5,3]) # create tensor from data 
print(x)

tensor([5.5000, 3.0000])


In [13]:
# if we create tensor from existing tensor, those will reuse properties of previous tensor unless we specify it.
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
x = torch.randn_like(x,dtype=torch.float) # overriding dtype
print(x)

tensor([[ 0.7555, -1.1599,  1.1200],
        [-0.1467, -0.0316, -0.1302],
        [-0.6633,  0.7182, -0.1888],
        [-0.7062,  1.4989,  0.3799],
        [ 0.5235,  0.4764, -0.3301]])


In [16]:
print(x.size()) # torch.size is tuple so it can support all tuple operations

torch.Size([5, 3])


In [20]:
# operations 
y = torch.rand(5,3)
# print(x)
# print(y)
print(x + y) # adding 
print(torch.add(x,y)) # adding syntax 2 
result = torch.empty(5,3) # uninitialized tensor 
torch.add(x,y,out=result) # giving result tensor for result 
print(result)

tensor([[ 1.2537, -0.2999,  1.4197],
        [ 0.2697,  0.0628,  0.0345],
        [-0.3405,  1.0015,  0.4198],
        [-0.1880,  2.1193,  1.3680],
        [ 0.6051,  1.3132, -0.2442]])
tensor([[ 1.2537, -0.2999,  1.4197],
        [ 0.2697,  0.0628,  0.0345],
        [-0.3405,  1.0015,  0.4198],
        [-0.1880,  2.1193,  1.3680],
        [ 0.6051,  1.3132, -0.2442]])
tensor([[ 1.2537, -0.2999,  1.4197],
        [ 0.2697,  0.0628,  0.0345],
        [-0.3405,  1.0015,  0.4198],
        [-0.1880,  2.1193,  1.3680],
        [ 0.6051,  1.3132, -0.2442]])


In [21]:
y.add_(x) # adds x to y and updates y with result 
print(y)
# all the operations which has post-fixed _ will mutate the tensor 

tensor([[ 1.2537, -0.2999,  1.4197],
        [ 0.2697,  0.0628,  0.0345],
        [-0.3405,  1.0015,  0.4198],
        [-0.1880,  2.1193,  1.3680],
        [ 0.6051,  1.3132, -0.2442]])


In [23]:
# standard numpy indexing would work 
print(x)
print(x[:,1]) # second column 

tensor([[ 0.7555, -1.1599,  1.1200],
        [-0.1467, -0.0316, -0.1302],
        [-0.6633,  0.7182, -0.1888],
        [-0.7062,  1.4989,  0.3799],
        [ 0.5235,  0.4764, -0.3301]])
tensor([-1.1599, -0.0316,  0.7182,  1.4989,  0.4764])


In [25]:
# resizing or reshape tensor 
x = torch.randn(4,4)
y = x.view(16)
z = x.view(2,8)
k = x.view(8,2)
print(x.size(), y.size(), z.size(), k.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([8, 2])


In [28]:
print(x)
print(y)

tensor([[-1.3787,  0.3541,  1.8292, -2.3544],
        [-0.4944,  0.4232,  0.0333, -1.3215],
        [-1.4336, -0.3259, -1.4277, -1.7809],
        [-1.3686, -0.2238,  1.5356,  0.9251]])
tensor([-1.3787,  0.3541,  1.8292, -2.3544, -0.4944,  0.4232,  0.0333, -1.3215,
        -1.4336, -0.3259, -1.4277, -1.7809, -1.3686, -0.2238,  1.5356,  0.9251])


In [29]:
print(z)
print(k)

tensor([[-1.3787,  0.3541,  1.8292, -2.3544, -0.4944,  0.4232,  0.0333, -1.3215],
        [-1.4336, -0.3259, -1.4277, -1.7809, -1.3686, -0.2238,  1.5356,  0.9251]])
tensor([[-1.3787,  0.3541],
        [ 1.8292, -2.3544],
        [-0.4944,  0.4232],
        [ 0.0333, -1.3215],
        [-1.4336, -0.3259],
        [-1.4277, -1.7809],
        [-1.3686, -0.2238],
        [ 1.5356,  0.9251]])


In [30]:
# if we have one element tensor, use .item() to get value as python number
x = torch.randn(1)
print(x)
print(x.item()) # numpy number 

tensor([0.8543])
0.8542513251304626


In [31]:
# TENSOR --> NUMPY 
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [33]:
a.add_(1) # numpy array will change as well 
print(a)

tensor([2., 2., 2., 2., 2.])


In [35]:
print(b)

[2. 2. 2. 2. 2.]


In [39]:
# NUMPY ARRAY --> TENSOR 
import numpy as np 
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [42]:
# CUDA TENSORS 
# Tensors could be moved to any device using .to method 

if torch.cuda.is_available(): 
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) # creating directly on GPU 
    x = x.to(device) # copying x to GPU 
    z = x + y # adding in CUDA
    print(z) 
    print(z.to("cpu", torch.double)) # moving it back to CPU 

tensor([1.8543], device='cuda:0')
tensor([1.8543], dtype=torch.float64)
